#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SlideDatetimePickerCSharp.Resource", IsApplication=false)]

namespace SlideDatetimePickerCSharp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public static int gray_holo_dark = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int gray_holo_light = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int selection_divider = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060006
			public static int buttonHorizontalDivider = 2131099654;
			
			// aapt resource value: 0x7f060008
			public static int buttonVerticalDivider = 2131099656;
			
			// aapt resource value: 0x7f060007
			public static int cancelButton = 2131099655;
			
			// aapt resource value: 0x7f060000
			public static int customTab = 2131099648;
			
			// aapt resource value: 0x7f060002
			public static int datePicker = 2131099650;
			
			// aapt resource value: 0x7f060009
			public static int okButton = 2131099657;
			
			// aapt resource value: 0x7f060004
			public static int slidingTabLayout = 2131099652;
			
			// aapt resource value: 0x7f060001
			public static int tabText = 2131099649;
			
			// aapt resource value: 0x7f060003
			public static int timePicker = 2131099651;
			
			// aapt resource value: 0x7f060005
			public static int viewPager = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int Custom_Tab = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int Fragment_Date = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int Fragment_Time = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int Slide_Date_Time_Picker = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public static int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public static int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
